#!/bin/sh

requiredyarnver=1.22
requirednodever=v12

# Check versions
version_greater_equal () {
  if ! printf '%s\n' "$2" "$1" | sort -c -V 2>/dev/null
  then
      printf 'Error! Need %s version %s or above\n' "$3" "$2" >&2
      return 1
  fi
}

version_greater_equal "$(yarn --version)" "$requiredyarnver" "yarn" || exit
version_greater_equal "$(node --version)" "$requirednodever" "node" || exit

# Install
yarn

# Generate data using ../data-files as default path
DF=${1:-../data-files}
printf 'Using data files from %s\n' "$DF"

yarn start "$DF"
