// headers: the table columns of each database, as Human-GEM names them (metKEGGID) and as
// yeast-GEM names them after the annotation keys (kegg.compound)
const crossReferencesDict = {
  ratcon: {
    headers: ["rxnRatconID"],
    db: "Ratcon",
    dbPrefix: "",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  spontaneous: {
    headers: ["spontaneous"],
    db: "spontaneous",
    dbPrefix: "",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  tcdb: {
    headers: ["rxnTCDBID"],
    db: "TCDB",
    dbPrefix: "",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  hmr2: {
    headers: ["rxnHMR2ID", "metHMR2ID"],
    db: "HMR 2.0",
    dbPrefix: "",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  recon3dreact: {
    headers: ["rxnRecon3DID"],
    db: "Recon3D",
    dbPrefix: "vmhreaction",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  recon3dmet: {
    headers: ["metRecon3DID"],
    db: "Recon3D",
    dbPrefix: "vmhmetabolite",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  hepatonet1: {
    headers: ["rxnHepatoNET1ID", "metHepatoNET1ID"],
    db: "HepatoNET1",
    dbPrefix: "",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  ehmn: {
    headers: ["rxnEHMNID", "metEHMNID"],
    db: "EHMN",
    dbPrefix: "",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  lipidmaps: {
    headers: ["metLipidMapsID"],
    db: "LipidMaps",
    dbPrefix: "lipidmaps",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  pubchem: {
    headers: ["metPubChemID"],
    db: "PubChem",
    dbPrefix: "pubchem",
    compoundSuffix: ".compound",
    reactionSuffix: "",
    geneSuffix: "",
  },
  hmdb: {
    headers: ["metHMDBID"],
    db: "HMDB",
    dbPrefix: "hmdb",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  ensembl: {
    headers: ["geneEnsemblID"],
    db: "Ensembl",
    dbPrefix: "ensembl",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  proteinatlas: {
    headers: ["geneProteinAtlasID"],
    db: "Protein Atlas",
    dbPrefix: "hpa",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  entrez: {
    headers: ["geneEntrezID"],
    db: "NCBI Gene",
    dbPrefix: "ncbigene",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  enst: {
    headers: ["geneENSTID"],
    db: "Ensembl transcript",
    dbPrefix: "ensembl",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  ensp: {
    headers: ["geneENSPID"],
    db: "Ensembl protein",
    dbPrefix: "ensembl",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  kegg: {
    headers: ["rxnKEGGID", "metKEGGID", "kegg.reaction", "kegg.compound"],
    db: "KEGG",
    dbPrefix: "kegg",
    compoundSuffix: ".compound",
    reactionSuffix: ".reaction",
    geneSuffix: "",
  },
  meta_net_x: {
    headers: ["rxnMetaNetXID", "metMetaNetXID", "metanetx.reaction", "metanetx.chemical"],
    db: "MetaNetX",
    dbPrefix: "metanetx",
    compoundSuffix: ".chemical",
    reactionSuffix: ".reaction",
    geneSuffix: "",
  },
  rhea: {
    headers: ["rxnRheaID", "metRheaID"],
    db: "Rhea",
    dbPrefix: "rhea",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  rheamaster: {
    headers: ["rxnRheaMasterID"],
    db: "RheaMaster",
    dbPrefix: "rhea",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  model_seed: {
    headers: ["metSeedID", "rxnSeedID"],
    db: "ModelSEED",
    dbPrefix: "seed",
    compoundSuffix: ".compound",
    reactionSuffix: ".reaction",
    geneSuffix: "",
  },
  bigg: {
    headers: ["rxnBiGGID", "metBiGGID", "bigg.reaction", "bigg.metabolite"],
    db: "BiGG",
    dbPrefix: "bigg",
    compoundSuffix: ".metabolite",
    reactionSuffix: ".reaction",
    geneSuffix: "",
  },
  metacyc: {
    headers: [],
    db: "MetaCyc",
    dbPrefix: "metacyc",
    compoundSuffix: ".compound",
    reactionSuffix: ".reaction",
    geneSuffix: "",
  },
  sabio_rk: {
    headers: [],
    db: "SABIO-RK",
    dbPrefix: "sabiork",
    compoundSuffix: ".compound",
    reactionSuffix: ".reaction",
    geneSuffix: "",
  },
  chebi: {
    headers: ["metChEBIID", "chebi"],
    db: "ChEBI",
    dbPrefix: "CHEBI",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  reactome: {
    headers: ["rxnREACTOMEID"],
    db: "Reactome",
    dbPrefix: "reactome",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  ncbigene: {
    headers: ["geneEntrezID"],
    db: "NCBI Protein",
    dbPrefix: "ncbiprotein",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
  uniprot: {
    headers: ["geneUniProtID", "uniprot"],
    db: "UniProtKB",
    dbPrefix: "uniprot",
    compoundSuffix: "",
    reactionSuffix: "",
    geneSuffix: "",
  },
};

export { crossReferencesDict };
